### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by awillis** [rainliu/gocl#4]
I encountered the following error:

$ go build -tags="cl20" github.com/rainliu/gocl/cl
# github.com/rainliu/gocl/cl
go/src/github.com/rainliu/gocl/cl/image12.go:47: c_image_desc.buffer undefined (type C.struct__cl_image_desc has no field or method buffer)
go/src/github.com/rainliu/gocl/cl/queue20.go:39: cannot use c_properties_ptr (type *C.cl_command_queue_properties) as type *C.cl_queue_properties in argument to _Cfunc_clCreateCommandQueueWithProperties

I'm using AMD-APP-SDK-v3.0.124.132-GA-linux64.sh and fglrx-14.502.1040 on a FirePro W7100.
My environment looks like this:
$ cat /etc/profile.d/AMDAPPSDK.sh 
export AMDAPPSDKROOT=/opt/AMDAPPSDK-3.0
export AMDAPPSDKROOT=/opt/AMDAPPSDK-3.0
export LD_LIBRARY_PATH="/opt/AMDAPPSDK-3.0/lib/x86_64/"
export CGO_CFLAGS=-I$AMDAPPSDKROOT/include
export CGO_LDFLAGS=-L$AMDAPPSDKROOT/lib/x86_64

Any help would be greatly appreciated!

**Comment by awillis** [comment]
The cl_image_desc would seem to have a field named 'buffer' as per the spec
https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/imageDescriptor.html

Here is what I found in /opt/AMDAPPSDK-3.0/include/CL/cl.h:

typedef struct _cl_image_desc {
    cl_mem_object_type      image_type;
    size_t                  image_width;
    size_t                  image_height;
    size_t                  image_depth;
    size_t                  image_array_size;
    size_t                  image_row_pitch;
    size_t                  image_slice_pitch;
    cl_uint                 num_mip_levels;
    cl_uint                 num_samples;
#ifdef __GNUC__
    __extension__   /* Prevents warnings about anonymous union in -pedantic builds */
#endif
    union {
      cl_mem                  buffer;
      cl_mem                  mem_object;
    };
} cl_image_desc;

**Comment by rainliu** [comment]
Please change the following 

export CGO_CFLAGS=-I$AMDAPPSDKROOT/include

To
export CGO_CFLAGS=-I$GOPATH/src/gocl/android/include
