### ISSUE TITLE
heavy memory leak when run in a loop

### ISSUE THREAD

**Issue by jolan** [rainliu/gocl#9]
We noticed that our [gominer](https://github.com/decred/gominer/) project that uses your library leaks memory in proportion to how fast the main loop is running on the device.

I was able to reproduce the issue by forcing one of the demos to run in a loop:

https://github.com/rainliu/gocl/compare/master...jolan:jolan_memleak

It leaks about 1MB/s on my machine.  Looking through the source code there's only a few files that are freeing any memory.  Unfortunately, I'm not very well versed in C/cgo memory management but will start digging to see if I can help fix this.

**Comment by rainliu** [comment]
could you try use default global_work_offset/size/local_work_size by setting them to nil?


err = cl.CLEnqueueNDRangeKernel(queue, kernel, 1, nil, nil, nil, 0, nil, nil)


Looks like Go GC not start yet during the loop.


--
Best regards,

Yu Liu
________________________________

**Comment by jolan** [comment]
I think that will help a bit but simply running cl.CLEnqueueReadBuffer in a loop leaks lots of memory as well.

**Comment by rainliu** [comment]
if only running cl.CLEnqueueReadBuffer in a loop leaks lots of memory as well, then I think it is OpenCL C library issue, instead of gocl issue. 

You can try C version of this test to check it.
